import type { PoolClient } from 'pg';
import pool from '../database/connection.js';
import { HttpError } from '../utils/httpError.js';

type Actor = { id: number };
const inventorySelect = `SELECT i.id, i.item_id AS "itemId", i.location_id AS "locationId", i.batch_number AS "batchNumber", i.physical_quantity AS "physicalQuantity", i.reserved_quantity AS "reservedQuantity", i.physical_quantity - i.reserved_quantity AS "availableQuantity", it.sku, it.name AS "itemName", l.name AS "locationName" FROM inventory i JOIN items it ON it.id = i.item_id JOIN locations l ON l.id = i.location_id`;

async function movement(client: PoolClient, inventory: any, type: 'IN' | 'OUT' | 'ADJUSTMENT', quantity: number, referenceType: string, referenceId: number | null, actor: Actor) {
  await client.query(`INSERT INTO inventory_movements (inventory_id,item_id,location_id,batch_number,movement_type,quantity,reference_type,reference_id,created_by_user_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`, [inventory.id, inventory.item_id, inventory.location_id, inventory.batch_number, type, quantity, referenceType, referenceId, actor.id]);
}

export async function listInventory() { return (await pool.query(`${inventorySelect} ORDER BY i.id`)).rows; }
export async function createInventory(data: any, actor: Actor) {
  const client = await pool.connect();
  try { await client.query('BEGIN'); const result = await client.query(`INSERT INTO inventory (item_id,location_id,batch_number,physical_quantity,reserved_quantity) VALUES ($1,$2,$3,$4,$5) RETURNING *`, [data.itemId,data.locationId,data.batchNumber,data.physicalQuantity,data.reservedQuantity]); const row = result.rows[0]; if (data.physicalQuantity) await movement(client,row,'IN',data.physicalQuantity,'INVENTORY_CREATE',null,actor); await client.query('COMMIT'); return (await pool.query(`${inventorySelect} WHERE i.id=$1`, [row.id])).rows[0]; } catch (e: any) { await client.query('ROLLBACK'); if (e.code === '23505') throw new HttpError(409,'Inventory batch already exists'); throw e; } finally { client.release(); }
}
export async function updateInventory(id: number, data: any, actor: Actor) {
 const client=await pool.connect(); try { await client.query('BEGIN'); const found=await client.query('SELECT * FROM inventory WHERE id=$1 FOR UPDATE',[id]); if(!found.rowCount) throw new HttpError(404,'Inventory not found'); const row=found.rows[0]; const physical=data.physicalQuantity ?? row.physical_quantity, reserved=data.reservedQuantity ?? row.reserved_quantity; if(reserved>physical) throw new HttpError(422,'Reserved quantity cannot exceed physical quantity'); await client.query('UPDATE inventory SET physical_quantity=$1,reserved_quantity=$2 WHERE id=$3',[physical,reserved,id]); const delta=physical-row.physical_quantity; if(delta) await movement(client,row,'ADJUSTMENT',delta,'INVENTORY_ADJUSTMENT',id,actor); await client.query('COMMIT'); return (await pool.query(`${inventorySelect} WHERE i.id=$1`,[id])).rows[0]; } catch(e){ await client.query('ROLLBACK'); throw e; } finally{client.release();}
}

export async function listWorkOrders() { return (await pool.query(`SELECT w.id,w.work_order_id AS "workOrderId",w.required_quantity AS "requiredQuantity",w.status,w.assigned_user_id AS "assignedUserId",u.username AS "assignedUser",w.location_id AS "locationId",l.name AS "locationName",w.item_id AS "itemId",it.name AS "itemName",COALESCE(SUM(i.physical_quantity-i.reserved_quantity),0)::int AS "availableQuantity",GREATEST(w.required_quantity-COALESCE(SUM(i.physical_quantity-i.reserved_quantity),0),0)::int AS shortage FROM work_orders w JOIN locations l ON l.id=w.location_id JOIN items it ON it.id=w.item_id LEFT JOIN users u ON u.id=w.assigned_user_id LEFT JOIN inventory i ON i.item_id=w.item_id AND i.location_id=w.location_id GROUP BY w.id,u.username,l.name,it.name ORDER BY w.id`)).rows; }
export async function createWorkOrder(data:any) { const result=await pool.query(`INSERT INTO work_orders (work_order_id,location_id,item_id,required_quantity,assigned_user_id,status) VALUES ($1,$2,$3,$4,$5,'ASSIGNED') RETURNING id`,[data.workOrderId,data.locationId,data.itemId,data.requiredQuantity,data.assignedUserId ?? null]); return (await listWorkOrders()).find((row:any)=>row.id===result.rows[0].id); }
export async function updateWorkOrderStatus(id:number,status:string) { const current=await pool.query('SELECT status FROM work_orders WHERE id=$1',[id]); if(!current.rowCount) throw new HttpError(404,'Work order not found'); const transitions:Record<string,string[]>={ASSIGNED:['IN_PROGRESS'],IN_PROGRESS:['COMPLETED'],COMPLETED:[]}; if(!transitions[current.rows[0].status].includes(status)) throw new HttpError(409,'Invalid work order status transition'); await pool.query('UPDATE work_orders SET status=$1 WHERE id=$2',[status,id]); return (await listWorkOrders()).find((row:any)=>row.id===id); }

export async function listTransfers() { return (await pool.query(`SELECT t.id,t.transfer_id AS "transferId",t.source_location_id AS "sourceLocationId",t.destination_location_id AS "destinationLocationId",t.item_id AS "itemId",t.quantity,t.status,sl.name AS "sourceLocation",dl.name AS "destinationLocation",it.name AS "itemName" FROM internal_transfers t JOIN locations sl ON sl.id=t.source_location_id JOIN locations dl ON dl.id=t.destination_location_id JOIN items it ON it.id=t.item_id ORDER BY t.id`)).rows; }
export async function createTransfer(data:any) { const result=await pool.query(`INSERT INTO internal_transfers (transfer_id,source_location_id,destination_location_id,item_id,quantity,status) VALUES ($1,$2,$3,$4,$5,'REQUESTED') RETURNING id`,[data.transferId,data.sourceLocationId,data.destinationLocationId,data.itemId,data.quantity]); return (await listTransfers()).find((row:any)=>row.id===result.rows[0].id); }
export async function dispatchTransfer(id:number,actor:Actor) { const client=await pool.connect(); try { await client.query('BEGIN'); const transfer=(await client.query('SELECT * FROM internal_transfers WHERE id=$1 FOR UPDATE',[id])).rows[0]; if(!transfer) throw new HttpError(404,'Transfer not found'); if(transfer.status!=='REQUESTED') throw new HttpError(409,'Only requested transfers can be dispatched'); const source=(await client.query('SELECT * FROM inventory WHERE item_id=$1 AND location_id=$2 ORDER BY id LIMIT 1 FOR UPDATE',[transfer.item_id,transfer.source_location_id])).rows[0]; if(!source || source.physical_quantity-source.reserved_quantity<transfer.quantity) throw new HttpError(422,'Insufficient source available stock'); await client.query('UPDATE inventory SET physical_quantity=physical_quantity-$1 WHERE id=$2',[transfer.quantity,source.id]); await movement(client,source,'OUT',-transfer.quantity,'TRANSFER_DISPATCH',id,actor); await client.query(`UPDATE internal_transfers SET status='DISPATCHED',updated_at=CURRENT_TIMESTAMP WHERE id=$1`,[id]); await client.query('COMMIT'); return (await listTransfers()).find((row:any)=>row.id===id); } catch(e){await client.query('ROLLBACK');throw e;} finally{client.release();} }
export async function receiveTransfer(id:number,actor:Actor) { const client=await pool.connect(); try { await client.query('BEGIN'); const transfer=(await client.query('SELECT * FROM internal_transfers WHERE id=$1 FOR UPDATE',[id])).rows[0]; if(!transfer) throw new HttpError(404,'Transfer not found'); if(transfer.status!=='DISPATCHED') throw new HttpError(409,'Only dispatched transfers can be received'); let destination=(await client.query('SELECT * FROM inventory WHERE item_id=$1 AND location_id=$2 ORDER BY id LIMIT 1 FOR UPDATE',[transfer.item_id,transfer.destination_location_id])).rows[0]; if(!destination){ const inserted=await client.query(`INSERT INTO inventory (item_id,location_id,batch_number,physical_quantity,reserved_quantity) VALUES ($1,$2,$3,$4,0) RETURNING *`,[transfer.item_id,transfer.destination_location_id,`TRANSFER-${id}`,0]); destination=inserted.rows[0]; } await client.query('UPDATE inventory SET physical_quantity=physical_quantity+$1 WHERE id=$2',[transfer.quantity,destination.id]); await movement(client,destination,'IN',transfer.quantity,'TRANSFER_RECEIPT',id,actor); await client.query(`UPDATE internal_transfers SET status='RECEIVED',updated_at=CURRENT_TIMESTAMP WHERE id=$1`,[id]); await client.query('COMMIT'); return (await listTransfers()).find((row:any)=>row.id===id); } catch(e){await client.query('ROLLBACK');throw e;} finally{client.release();} }
