import { Router } from 'express';
import { authenticate } from '../middleware/authenticate.js';
import { authorize } from '../middleware/authorize.js';
import * as controller from '../controllers/operationsController.js';
const router=Router();
const operational=[authenticate,authorize(['ADMIN','OPERATIONS_USER'])];
router.get('/inventory',...operational,controller.getInventory); router.post('/inventory',...operational,controller.postInventory); router.patch('/inventory/:id',...operational,controller.patchInventory);
router.get('/work-orders',...operational,controller.getWorkOrders); router.post('/work-orders',...operational,controller.postWorkOrder); router.patch('/work-orders/:id/status',...operational,controller.patchWorkOrder);
router.get('/transfers',...operational,controller.getTransfers); router.post('/transfers',...operational,controller.postTransfer); router.post('/transfers/:id/dispatch',...operational,controller.dispatch); router.post('/transfers/:id/receive',...operational,controller.receive);
export default router;
